name: submit

on:
  # schedule:
  #   - cron: '0 1 * * *'
  #   # 每天9点准时提交
  push:
    branches:
      - master
    
jobs:
  punch:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 15.8.0
      - name: install pkgs
        run: npm install
      - name: punch in
        run: node index.js ${{secrets.SENDER}} ${{secrets.PASS}}
      
